version: "3"
services:
  node:
    image: mhart/alpine-node:latest
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    env_file:
    - .env
    volumes:
      - ./:/home/node/app
    expose:
      - 8081
    command: npm start