version: "3"
services:
  mongo:
    image: mongo
    container_name: database
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    expose:
      - 27017

  redis:
    image: redis:alpine
    container_name: cache
    expose:
      - 6379
  
  node:
    image: node:lts-alpine
    container_name: app
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: npm start
    links:
      - redis
      - mongo